#index:
#    path: /
#    controller: App\Controller\DefaultController::index

one.to.one:
  path: /one/to/one
  controller: App\Controller\IndexController::index

messenger.default:
  path: /messenger/default
  controller: App\Controller\IndexController::message

doctrine.curd.one.to.one:
  path: /curd/one/{uid}
  controller: App\Controller\IndexController::curdOneToOne

doctrine.curd.one.to.many.double:
  path: /curd/one/many/double/{pid}
  controller: App\Controller\IndexController::curdOneToMany