#index:
#    path: /
#    controller: App\Controller\DefaultController::index

one.to.one:
  path: /one/to/one
  controller: App\Controller\IndexController::index

messenger.default:
  path: /messenger/default
  controller: App\Controller\IndexController::message